### ISSUE TITLE
Single-day Event list shows all-day events for following day

### ISSUE THREAD

**Issue by dml105** [marksie1988/atomic_calendar#1610]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I have a set of ACR cards, each displaying exactly one day of events, with varying offsets. 

As an example, this results in correctly presenting an event for Wed Jan 29 (an event from 6-9pm) but also incorrectly presents the whole day event for Thu Jan 30.

![Image](https://github.com/user-attachments/assets/47e5726a-41ca-4728-81eb-b5117432130b)

That event on Thu Jan 30 should not appear on a 1 day event list. 

### Expected behaviour

<img width="489" alt="Image" src="https://github.com/user-attachments/assets/cef2bd5f-1cff-4f8c-868d-76cfdf40c5d7" />

### Steps To Reproduce

For example: 

```
type: custom:atomic-calendar-revive
name: Calendar
enableModeChange: true
entities:
  - entity: calendar.school_calendar
    name: School
  - entity: calendar.family_calendar
    name: Family calendar
  - entity: calendar.Mom
    name: Mom
  - entity: calendar.Dad
    name: Dad
maxDaysToShow: 1
startDaysAhead: 3
```

Note: these are ICS calendars using the CALDAV integration. It appears the problem does not occur with calendars from the Google Calendar integration. 

### Mode

Event (default)

### Card Version

10.0.0

### Home Assistant Version

2014.12.3

### Configuration

```shell

```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
