### ISSUE TITLE
icon of the next month weeks shown overlapping edge of the calendar

### ISSUE THREAD

**Issue by stepir** [marksie1988/atomic_calendar#1627]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hi just using this code:

```
type: custom:atomic-calendar-revive
defaultMode: Calendar
showMultiDay: true
entities:
  - entity: calendar.calendario_diesel
    color: sandybrown
  - entity: calendar.calendario_fresh
    color: royalblue
  - entity: calendar.calendario_grey
    name: Calendario Grey
    color: darkkhaki
  - entity: calendar.calendario_black
    name: Calendario Black
    color: sienna
showMonth: true
showWeekNumbers: false
maxDaysToShow: 60
multiDayEvent: true
highlightToday: true
disableCalLink: true
hideDuplicates: true
showLastCalendarWeek: false
calShowDescription: true
dateFormat: LL
showMultiDayEventParts: true
compactMode: false
showDatePerEvent: true
showDescription: true
showEventIcon: true
showEventDate: true
showTimeRemaining: true
showRelativeTime: true
showProgressBar: true
linkToEvent: true
```

produce this effect:

![Image](https://github.com/user-attachments/assets/da4d8daf-c67c-4b7e-87cd-bb4e3ae6de8a)

### Expected behaviour

can you see the icon of the last event being rendered on the lower edge?

![Image](https://github.com/user-attachments/assets/b7496ef9-dde7-41b9-96de-666141cf8da4)

### Mode

Calendar

### Card Version

v10

### Home Assistant Version

2025.2.5

### Configuration

```shell
supervised
```

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
