### ISSUE TITLE
Time format broken in V5.0

### ISSUE THREAD

**Issue by garyak** [marksie1988/atomic_calendar#510]
Following an update to version 5.0, event times being displayed are bad.
## Expected behaviour

Event times should appear in 12 hour format for MST as specified in the config.
## Current behaviour

Event times are unrecognizable.
## Steps to reproduce

No steps needed.

## Custom values

```
dateColor: black
dateFormat: dddd, MMMM D
dateSize: 80
dayWrapperLineColor: black
dimFinishedEvents: true
enableModeChange: true
entities:
  - entity: calendar.garyk_wildriders_org
    icon: mdi:skull
    titleColor: CornflowerBlue
  - color: red
    entity: calendar.holidays_in_united_states
    icon: mdi:star
    titleColor: CornflowerBlue
  - entity: calendar.kelleycalendar
    icon: mdi:alien
    titleColor: CornflowerBlue
eventBarColor: blue
finishedEventFilter: grayscale(100%)
finishedEventOpacity: 0.6
firstDayOfWeek: 7
hideFinishedEvents: true
hoursFormat: 12h
locationIconColor: rgb(230, 124, 115)
locationLinkColor: black
locationTextSize: 90
maxDaysToShow: 10
name: Events
progressBarColor: blue
showColors: true
showCurrentEventLine: false
showWeekDay: true
showDate: true
showLastCalendarWeek: false
showLoader: false
showLocation: true
showMonth: true
showProgressBar: false
showRelativeTime: false
timeColor: rgb(100, 100, 100)
timeSize: 90
titleColor: black
calActiveEventBackgroundColor: rgb(256, 256, 256)
titleSize: 100
type: custom:atomic-calendar-revive
disableLocationLink: false
showDescription: false
refreshInterval: 60
disableEventLink: true
```

## Your environment

Version | core-2021.10.5
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.70
CPU Architecture | x86_64
Timezone | America/Denver

## Checklist

- [x] I searched the current issues and the issue is not known.
- [x] I searched the troubleshooting and there's no fix available for this bug.
- [] I searched on Google, YouTube, Reddit and there's no fix.
- [x] I am mostly sure that the problem is related to the code and isn't my fault.
![atomic](https://user-images.githubusercontent.com/47036329/137585862-b4c8b2d4-d314-4c5a-91b1-57b5d7efe3a4.jpg)
